version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: geiksmysql299  
      MYSQL_DATABASE: feedme
    volumes:
    - ./backend/database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks: 
      - app-network

  addrating:
    build:
      context: ./backend/addRating 
      dockerfile: Dockerfile
    container_name: addRatingContainer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: geiksmysql299
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - app-network

  addrestaurant:
    build:
      context: ./backend/addRestaurant 
      dockerfile: Dockerfile
    container_name: addRestaurantContainer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: geiksmysql299
    ports:
      - "3004:3004"
    depends_on:
      - mysql
    networks:
      - app-network

  displayservice:
    build:
      context: ./backend/displayService  
      dockerfile: Dockerfile
    container_name: displayServiceContainer
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: geiksmysql299
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    container_name: frontendContainer
    ports:
      - "3003:3003"  
    networks:
      - app-network
    depends_on:
      - addrating
      - addrestaurant
      - displayservice   


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
    ports:
      - "9090:9090"  
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafanaContainer
    ports:
      - "3007:3000"  
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

