apiVersion: apps/v1
kind: Deployment
metadata:
  name: addrating-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addrating
  template:
    metadata:
      labels:
        app: addrating
    spec:
      containers:
      - name: addratingcontainer
        image: europe-west1-docker.pkg.dev/agisit-2425-website-26/feedmerepo/addrating:latest
        ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: addrating-service
  labels:
    app: addrating
spec:
  type: ClusterIP  # Change to LoadBalancer if you want external access
  selector:
    app: addrating  # This should match the label in your deployment
  ports:
    - protocol: TCP
      port: 3001           # The port that will be exposed
      targetPort: 3001