apiVersion: apps/v1
kind: Deployment
metadata:
  name: addrating-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addrating
  template:
    metadata:
      labels:
        app: addrating
    spec:
      containers:
      - name: addratingcontainer
        image: europe-west1-docker.pkg.dev/agisit-2425-website-26/feedmerepo/addrating:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "mysql"  
        - name: DB_USER
          value: "feedme_user"   
        - name: DB_PASSWORD
          value: "feedmelisbon"  
        - name: DB_NAME
          value: "feedme_database"  

---

apiVersion: v1
kind: Service
metadata:
  name: addrating-service
  labels:
    app: addrating
spec:
  type: ClusterIP  
  selector:
    app: addrating  
  ports:
    - protocol: TCP
      port: 3001           
      targetPort: 3001