apiVersion: apps/v1
kind: Deployment
metadata:
  name: addrestaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addrestaurant
  template:
    metadata:
      labels:
        app: addrestaurant
    spec:
      containers:
      - name: addrestaurantcontainer 
        image: europe-west1-docker.pkg.dev/agisit-2425-website-26/feedmerepo/addrestaurant:latest
        ports:
        - containerPort: 3004
        env:
        - name: DB_HOST
          value: "mysql"  
        - name: DB_USER
          value: "feedme_user"   
        - name: DB_PASSWORD
          value: "feedmelisbon" 
        - name: DB_NAME
          value: "feedme_database"  
---

apiVersion: v1
kind: Service
metadata:
  name: addrestaurant-service
  labels:
    app: addrestaurant
spec:
  type: ClusterIP  
  selector:
    app: addrestaurant 
  ports:
    - protocol: TCP
      port: 3004            
      targetPort: 3004      