---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    - name: Copy add_restaurant.yaml to the master node
      copy: 
        src: add_restaurant.yaml
        dest: /home/ubuntu/add_restaurant.yaml
        mode: 0777

    - name: Copy add_rating.yaml to the master node
      copy: 
        src: add_rating.yaml
        dest: /home/ubuntu/add_rating.yaml
        mode: 0777

    - name: Copy display_service.yaml to the master node
      copy: 
        src: display_service.yaml
        dest: /home/ubuntu/display_service.yaml
        mode: 0777


    - name: Copy frontend.yaml to the master node
      copy: 
        src: frontend.yaml
        dest: /home/ubuntu/frontend.yaml
        mode: 0777

    - name: Copy feedme_database.yaml to the master node
      copy: 
        src: feedme_database.yaml
        dest: /home/ubuntu/feedme_database.yaml
        mode: 0777

    - name: Copy grafana.yaml to the master node
      copy: 
        src: grafana.yaml
        dest: /home/ubuntu/grafana.yaml
        mode: 0777

    - name: Copy prometheus.yaml to the master node
      copy: 
        src: prometheus.yaml
        dest: /home/ubuntu/prometheus.yaml
        mode: 0777  

    - name: Copy test_service.yaml to the master node
      copy: 
        src: test_service.yaml
        dest: /home/ubuntu/test_service.yaml
        mode: 0777

    - name: Start addrestaurant deployment
      shell: sudo kubectl apply -f /home/ubuntu/add_restaurant.yaml

    - name: Start addrating deployment
      shell: sudo kubectl apply -f /home/ubuntu/add_rating.yaml

    - name: Start displayservice deployment
      shell: sudo kubectl apply -f /home/ubuntu/display_service.yaml

    - name: Start feedme_database deployment
      shell: sudo kubectl apply -f /home/ubuntu/feedme_database.yaml

    - name: Start prometheus deployment
      shell: sudo kubectl apply -f /home/ubuntu/prometheus.yaml

    - name: Start frontend deployment
      shell: sudo kubectl apply -f /home/ubuntu/frontend.yaml

    - name: Start grafana deployment
      shell: sudo kubectl apply -f /home/ubuntu/grafana.yaml

    - name: Start test_service deployment
      shell: sudo kubectl apply -f /home/ubuntu/test_service.yaml



