apiVersion: apps/v1
kind: Deployment
metadata:
  name: displayservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: displayservice
  template:
    metadata:
      labels:
        app: displayservice
    spec:
      containers:
      - name: displayservicecontainer
        image: europe-west1-docker.pkg.dev/agisit-2425-website-26/feedmerepo/displayservice:latest  
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: "mysql"  
        - name: DB_USER
          value: "feedme_user"  
        - name: DB_PASSWORD
          value: "feedmelisbon" 
        - name: DB_NAME
          value: "feedme_database"  
---

apiVersion: v1
kind: Service
metadata:
  name: displayservice-service
  labels:
    app: displayservice
spec:
  type: ClusterIP  
  selector:
    app: displayservice  
  ports:
    - protocol: TCP  
      port: 3002            
      targetPort: 3002