apiVersion: apps/v1
kind: Deployment
metadata:
  name: displayservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: displayservice
  template:
    metadata:
      labels:
        app: displayservice
    spec:
      containers:
      - name: displayservicecontainer
        image: europe-west1-docker.pkg.dev/agisit-2425-website-26/feedmerepo/displayservice:latest  
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: "mysql"  # Change to your database service name if different
        - name: DB_USER
          value: "feedme_user"   # Your database username
        - name: DB_PASSWORD
          value: "feedmelisbon"  # Your database password
        - name: DB_NAME
          value: "feedme_database"  # Your database name
---

apiVersion: v1
kind: Service
metadata:
  name: displayservice-service
  labels:
    app: displayservice
spec:
  type: ClusterIP  # Change to LoadBalancer if you want external access
  selector:
    app: displayservice  # This should match the label in your deployment
  ports:
    - protocol: TCP  
      port: 3002            # The port that will be exposed
      targetPort: 3002