apiVersion: v1
kind: ConfigMap
metadata: 
  name: prometheus-config
  labels: 
    app: prometheus
data: 
  prometheus.yml: | 
    global: 
      scrape_interval: 15s

    scrape_configs:
        - job_name: 'prometheus'  # Gi et navn til jobben
          static_configs:
            - targets: ['localhost:9090']  

        - job_name: 'display-service'  # Gi et navn til jobben
          static_configs:
            - targets: ['displayservice-service.default.svc.cluster.local:3002']  

        - job_name: 'addrating-service'  # Gi et navn til jobben
          static_configs:
            - targets: ['addrating-service.default.svc.cluster.local:3001'] 

        - job_name: 'addrestaurant-service'  # Gi et navn til jobben
          static_configs:
            - targets: ['addrestaurant-service.default.svc.cluster.local:3004']

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.37.0  # Official Prometheus image
        ports:
        - containerPort: 9090  # Default Prometheus port inside the container
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort  # Exposes the service on a port of each Node in the cluster
  ports:
  - port: 9090        # Port that the service will expose
    targetPort: 9090  # Port that the container listens on
  selector:
    app: prometheus